# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxonCli < Formula
  desc "Axon CLI tools"
  homepage "https://github.com/kamusis/axon-cli"
  version "0.3.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamusis/axon-cli/releases/download/v0.3.10/axon_0.3.10_darwin_amd64.tar.gz"
      sha256 "122db64c65350c5e7abff9a0e7f1b259176b8b1fcfa788f454b8fa20b2e572c5"

      define_method(:install) do
        bin.install "axon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamusis/axon-cli/releases/download/v0.3.10/axon_0.3.10_darwin_arm64.tar.gz"
      sha256 "ff181038eddd2baef80e92e958c7bbc87b0f1d135e23cf93938dcca226c05943"

      define_method(:install) do
        bin.install "axon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamusis/axon-cli/releases/download/v0.3.10/axon_0.3.10_linux_amd64.tar.gz"
      sha256 "5526bb8d5ee4773fd87cf9703ea438307efc316f9b4b766fd2c8c37fae2fecd7"
      define_method(:install) do
        bin.install "axon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamusis/axon-cli/releases/download/v0.3.10/axon_0.3.10_linux_arm64.tar.gz"
      sha256 "116f757a377717c7cb3c4ad45b871a4da267d85a7feaf02c59a69936c1510a6a"
      define_method(:install) do
        bin.install "axon"
      end
    end
  end

  test do
    system "#{bin}/axon", "--version"
  end
end
