# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AxonCli < Formula
  desc "Axon CLI tools"
  homepage "https://github.com/kamusis/axon-cli"
  version "0.3.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamusis/axon-cli/releases/download/v0.3.12/axon_0.3.12_darwin_amd64.tar.gz"
      sha256 "6c46fc0766a4cfb959da955b83cdef8da1050c7779371cce77c39a563bfab366"

      define_method(:install) do
        bin.install "axon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamusis/axon-cli/releases/download/v0.3.12/axon_0.3.12_darwin_arm64.tar.gz"
      sha256 "b885ae22b8edbf070db0411cf129f1e8c7a3c0bd7638ba79b1df394d16f42f4a"

      define_method(:install) do
        bin.install "axon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamusis/axon-cli/releases/download/v0.3.12/axon_0.3.12_linux_amd64.tar.gz"
      sha256 "d58fa72352dbb0a15e7f30970ab22f06bc0928cb82f8f7c1db03167a5cad887d"
      define_method(:install) do
        bin.install "axon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamusis/axon-cli/releases/download/v0.3.12/axon_0.3.12_linux_arm64.tar.gz"
      sha256 "12fd95a5527f4187e8caa7f59f96ca96e5c23b979f86cde6461e79ddd22a6c78"
      define_method(:install) do
        bin.install "axon"
      end
    end
  end

  test do
    system "#{bin}/axon", "--version"
  end
end
